import { prisma } from '@/lib/prisma'

export interface AutoTransactionData {
  type: 'PRODUCT_SALE' | 'ANIMAL_SALE' | 'CONSULTATION_FEE' | 'ADDITIONAL_CONSULTATION' | 'OTHER_INCOME'
  amount: number
  description: string
  paymentMethod?: string
  checkoutId?: number
  appointmentId?: number
  additionalFeeId?: number
  status?: 'PENDING' | 'COMPLETED' | 'CANCELLED'
}

/**
 * Auto-creates a transaction record in the CNS system
 * Called automatically when sales/payments occur
 */
export async function createAutoTransaction(data: AutoTransactionData) {
  try {
    const transaction = await prisma.transaction.create({
      data: {
        type: data.type,
        amount: data.amount,
        description: data.description,
        transactionDate: new Date(),
        paymentMethod: data.paymentMethod || null,
        status: data.status || 'COMPLETED',
        isAutoGenerated: true,
        checkoutId: data.checkoutId || null,
        appointmentId: data.appointmentId || null,
        additionalFeeId: data.additionalFeeId || null,
        notes: 'Auto-generated transaction',
      },
    })

    console.log(`[CNS] Auto-created transaction #${transaction.id}: ${data.type} - ${data.amount}`)
    return transaction
  } catch (error) {
    console.error('[CNS] Failed to create auto-transaction:', error)
    // Don't throw - we don't want to break the main transaction if CNS logging fails
    return null
  }
}

/**
 * Creates transaction for product sale
 */
export async function createProductSaleTransaction(
  checkoutId: number,
  amount: number,
  productName: string,
  paymentMethod?: string
) {
  return createAutoTransaction({
    type: 'PRODUCT_SALE',
    amount,
    description: `Product Sale: ${productName}`,
    paymentMethod,
    checkoutId,
    status: 'COMPLETED',
  })
}

/**
 * Creates transaction for animal sale
 */
export async function createAnimalSaleTransaction(
  checkoutId: number,
  amount: number,
  animalName: string,
  paymentMethod?: string
) {
  return createAutoTransaction({
    type: 'ANIMAL_SALE',
    amount,
    description: `Animal Sale: ${animalName}`,
    paymentMethod,
    checkoutId,
    status: 'COMPLETED',
  })
}

/**
 * Creates transaction for appointment consultation fee
 */
export async function createConsultationFeeTransaction(
  appointmentId: number,
  amount: number,
  doctorName: string,
  paymentMethod?: string
) {
  return createAutoTransaction({
    type: 'CONSULTATION_FEE',
    amount,
    description: `Consultation Fee - Dr. ${doctorName}`,
    paymentMethod,
    appointmentId,
    status: 'COMPLETED',
  })
}

/**
 * Creates transaction for additional consultation fee
 */
export async function createAdditionalConsultationTransaction(
  additionalFeeId: number,
  appointmentId: number,
  amount: number,
  description: string,
  paymentMethod?: string
) {
  return createAutoTransaction({
    type: 'ADDITIONAL_CONSULTATION',
    amount,
    description: `Additional Fee: ${description}`,
    paymentMethod,
    appointmentId,
    additionalFeeId,
    status: 'COMPLETED',
  })
}
