#!/usr/bin/env python3
"""
Adds Nginx static serving blocks for sitemap.xml and sub-sitemaps.
Run on VPS: sudo python3 fix-nginx-sitemaps.py

After running:
  sudo nginx -t && sudo systemctl reload nginx
  node generate-sitemaps.js   # generate the static XML files
  # Then resubmit sitemap.xml in GSC
"""

import re
import shutil
import subprocess
import sys
from datetime import datetime

NGINX_CONFIG = '/etc/nginx/sites-enabled/animalwellness'
PUBLIC_DIR = '/var/www/animalwellness/animal-nes/public'

SITEMAP_BLOCK = f"""
    # Serve sitemap index statically (generated by generate-sitemaps.js)
    location = /sitemap.xml {{
        root {PUBLIC_DIR}/sitemaps;
        try_files /index.xml =404;
        add_header Content-Type "application/xml; charset=utf-8";
        add_header Cache-Control "public, max-age=3600";
        access_log off;
    }}

    # Serve sub-sitemaps statically
    location ~ ^/sitemap/(?<smap_id>\\d+)(\\.xml)?$ {{
        root {PUBLIC_DIR}/sitemaps;
        try_files /$smap_id.xml =404;
        add_header Content-Type "application/xml; charset=utf-8";
        add_header Cache-Control "public, max-age=3600";
        access_log off;
    }}
"""

def main():
    # Read config
    with open(NGINX_CONFIG, 'r') as f:
        config = f.read()

    # Skip if already patched
    if 'generate-sitemaps.js' in config:
        print('Sitemap block already present — nothing to do.')
        sys.exit(0)

    # Backup
    backup = f'{NGINX_CONFIG}.bak.{datetime.now().strftime("%Y%m%d%H%M%S")}'
    shutil.copy2(NGINX_CONFIG, backup)
    print(f'Backup: {backup}')

    # Insert before the robots.txt block (or before the first location block)
    if 'location = /robots.txt' in config:
        config = config.replace(
            '    # Serve robots.txt statically',
            SITEMAP_BLOCK + '\n    # Serve robots.txt statically'
        )
    else:
        # Fallback: insert before the first location block
        config = re.sub(
            r'(\s+location\s)',
            SITEMAP_BLOCK + r'\1',
            config,
            count=1
        )

    with open(NGINX_CONFIG, 'w') as f:
        f.write(config)
    print('Nginx config updated.')

    # Test
    result = subprocess.run(['nginx', '-t'], capture_output=True, text=True)
    if result.returncode != 0:
        print('nginx -t FAILED — restoring backup')
        shutil.copy2(backup, NGINX_CONFIG)
        print(result.stderr)
        sys.exit(1)

    print('nginx -t OK')
    subprocess.run(['systemctl', 'reload', 'nginx'])
    print('Nginx reloaded.')
    print('\nNext steps:')
    print('  node generate-sitemaps.js')
    print('  Then resubmit https://animalwellness.shop/sitemap.xml in GSC → Sitemaps')

if __name__ == '__main__':
    main()
