import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const status = searchParams.get('status') || 'all';

    const where: any = {};
    if (status !== 'all') {
      where.status = status;
    }

    const requests = await prisma.premiumPartnershipRequest.findMany({
      where,
      include: {
        partner: {
          select: {
            id: true,
            partnerName: true,
            partnerEmail: true,
            shopName: true,
            partnerMobileNumber: true,
            partnerType: true,
            isPremium: true,
          },
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    return NextResponse.json({ requests });
  } catch (error) {
    console.error('Get premium requests error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function PUT(request: NextRequest) {
  try {
    const { requestId, action, notes } = await request.json();

    if (!requestId || !action) {
      return NextResponse.json(
        { error: 'Request ID and action are required' },
        { status: 400 }
      );
    }

    if (action !== 'approve' && action !== 'reject') {
      return NextResponse.json(
        { error: 'Invalid action. Must be approve or reject' },
        { status: 400 }
      );
    }

    const premiumRequest = await prisma.premiumPartnershipRequest.findUnique({
      where: { id: requestId },
      include: { partner: true },
    });

    if (!premiumRequest) {
      return NextResponse.json(
        { error: 'Request not found' },
        { status: 404 }
      );
    }

    if (premiumRequest.status !== 'pending') {
      return NextResponse.json(
        { error: 'This request has already been processed' },
        { status: 400 }
      );
    }

    // Update request status
    const updatedRequest = await prisma.premiumPartnershipRequest.update({
      where: { id: requestId },
      data: {
        status: action === 'approve' ? 'approved' : 'rejected',
        notes: notes || null,
      },
    });

    // If approved, update partner's isPremium status and record transaction
    if (action === 'approve') {
      const updatedPartner = await prisma.partner.update({
        where: { id: premiumRequest.partnerId },
        data: { isPremium: true },
        include: {
          referredBy: true
        }
      });

      // Record transaction in finance system
      const PREMIUM_PARTNERSHIP_FEE = 5000; // PKR
      await prisma.transaction.create({
        data: {
          type: 'OTHER_INCOME',
          amount: PREMIUM_PARTNERSHIP_FEE,
          description: `Premium Partnership Payment from ${premiumRequest.partner.partnerName} (Shop: ${premiumRequest.partner.shopName || 'N/A'})`,
          transactionDate: new Date(),
          paymentMethod: premiumRequest.paymentMethod,
          status: 'COMPLETED',
          isAutoGenerated: true,
          notes: `Auto-generated from premium partnership request #${requestId}`,
        },
      });

      // Add commission to referrer's wallet if they referred this partner
      if (updatedPartner.referredBy) {
        const referrerCommission = updatedPartner.referredBy.isPremium ? 1000 : 500; // PKR

        await prisma.partner.update({
          where: { id: updatedPartner.referredBy.id },
          data: {
            walletBalance: {
              increment: referrerCommission
            }
          }
        });

        console.log(`✅ Added ${referrerCommission} PKR commission to referrer ${updatedPartner.referredBy.partnerName}'s wallet`);
      }
    }

    return NextResponse.json({
      success: true,
      message: `Request ${action}d successfully`,
      request: updatedRequest,
    });
  } catch (error) {
    console.error('Update premium request error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
