import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    // Await the params object first
    const { id } = await params;
    const { status } = await request.json();
    const feeId = parseInt(id);

    if (!status || !['PENDING', 'PAID', 'CANCELLED'].includes(status)) {
      return NextResponse.json(
        { error: 'Invalid status' },
        { status: 400 }
      );
    }

    // Get the consultation fee with prescription details
    const consultationFee = await prisma.additionalConsultationFee.findUnique({
      where: { id: feeId },
      include: {
        prescription: {
          select: {
            doctorName: true,
          }
        }
      }
    });

    if (!consultationFee) {
      return NextResponse.json(
        { error: 'Consultation fee not found' },
        { status: 404 }
      );
    }

    // Update the fee status
    const updatedFee = await prisma.additionalConsultationFee.update({
      where: { id: feeId },
      data: { status },
    });

    // If status is being set to PAID, distribute the payment
    if (status === 'PAID' && consultationFee.status !== 'PAID') {
      const totalAmount = consultationFee.consultationFee;
      const doctorShare = totalAmount * 0.7; // 70% to doctor
      const revenueShare = totalAmount * 0.3; // 30% to revenue

      // Find the partner (doctor) by name
      const doctor = await prisma.partner.findFirst({
        where: {
          partnerName: consultationFee.prescription.doctorName
        }
      });

      if (doctor) {
        // Update doctor's wallet balance
        await prisma.partner.update({
          where: { id: doctor.id },
          data: {
            walletBalance: {
              increment: doctorShare
            }
          }
        });

        console.log(`[Payment Distribution] Consultation Fee #${feeId}:`);
        console.log(`  Total Amount: Rs. ${totalAmount.toFixed(2)}`);
        console.log(`  Doctor Share (70%): Rs. ${doctorShare.toFixed(2)} - Added to Dr. ${doctor.partnerName}'s wallet`);
        console.log(`  Revenue Share (30%): Rs. ${revenueShare.toFixed(2)}`);
      }

      // Update the transaction to reflect only the 30% revenue share
      // Find the auto-generated transaction for this consultation fee
      await prisma.transaction.updateMany({
        where: {
          additionalFeeId: feeId,
          isAutoGenerated: true
        },
        data: {
          amount: revenueShare, // Update to only the 30% revenue share
          notes: `Additional Consultation Fee - Total: Rs. ${totalAmount.toFixed(2)} | Doctor Share (70%): Rs. ${doctorShare.toFixed(2)} | Revenue Share (30%): Rs. ${revenueShare.toFixed(2)}`,
          updatedAt: new Date()
        }
      });
    }

    return NextResponse.json({
      success: true,
      data: updatedFee,
    });

  } catch (error) {
    console.error('Error updating additional consultation fee status:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}