import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/dashboard/",
          "/_next/",
          "/admin/",
          "/login/",
          "/checkout/",
          "/cart/",
          "/animalCart/",
          "/orders/",
          "/payment/",
          "/profile/",
          "/thankyou/",
          "/thank-you-*",
          "/prescriptionform/",
          "/historyform/",
          "/additional-consultation-fee/",
          "/jobApplicantForm/",
          "/jobvaccancyform/",
          "/quickjobform/",
          "/addProduct/",
          "/addCompany/",
          "/addPartner/",
          "/sell/",
          "/Privacy/",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: "/",
        disallow: [
          "/api/",
          "/dashboard/",
          "/_next/",
          "/admin/",
          "/login/",
          "/checkout/",
          "/cart/",
          "/animalCart/",
          "/orders/",
          "/payment/",
          "/profile/",
          "/thankyou/",
          "/thank-you-*",
          "/prescriptionform/",
          "/historyform/",
          "/additional-consultation-fee/",
          "/jobApplicantForm/",
          "/jobvaccancyform/",
          "/quickjobform/",
          "/addProduct/",
          "/addCompany/",
          "/addPartner/",
          "/sell/",
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: "https://www.animalwellness.shop/sitemap.xml",
  };
}