'use client';

import { useEffect, useState } from "react";
import axios from "axios";
import { Input } from "@/components/ui/input";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
    ChevronLeft,
    ChevronRight,
    Plus,
    Edit,
    Trash2,
    DollarSign,
    TrendingUp,
    Loader2,
} from "lucide-react";
import toast from "react-hot-toast";

interface Transaction {
    id: number;
    type: string;
    amount: number;
    description: string;
    transactionDate: string;
    paymentMethod?: string;
    status: string;
    isAutoGenerated: boolean;
    checkoutId?: number;
    appointmentId?: number;
    additionalFeeId?: number;
    notes?: string;
    createdAt: string;
}

export default function TransactionsPage() {
    const [transactions, setTransactions] = useState<Transaction[]>([]);
    const [search, setSearch] = useState("");
    const [typeFilter, setTypeFilter] = useState<string>("ALL");
    const [statusFilter, setStatusFilter] = useState<string>("ALL");
    const [sourceFilter, setSourceFilter] = useState<string>("ALL");
    const [limit, setLimit] = useState(10);
    const [page, setPage] = useState(1);
    const [total, setTotal] = useState(0);
    const [totalRevenue, setTotalRevenue] = useState(0);
    const [loading, setLoading] = useState(true);

    const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
    const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
    const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
    const [selectedTransaction, setSelectedTransaction] = useState<Transaction | null>(null);
    const [submitting, setSubmitting] = useState(false);

    const [formData, setFormData] = useState({
        type: "PRODUCT_SALE",
        amount: 0,
        description: "",
        transactionDate: new Date().toISOString().split('T')[0],
        paymentMethod: "",
        status: "COMPLETED",
        notes: "",
    });

    const transactionTypes = [
        "PRODUCT_SALE",
        "ANIMAL_SALE",
        "CONSULTATION_FEE",
        "ADDITIONAL_CONSULTATION",
        "OTHER_INCOME",
    ];

    const fetchData = async () => {
        try {
            setLoading(true);
            const params = new URLSearchParams({
                search,
                limit: limit.toString(),
                page: page.toString(),
            });

            if (typeFilter && typeFilter !== "ALL") {
                params.append("type", typeFilter);
            }

            if (statusFilter && statusFilter !== "ALL") {
                params.append("status", statusFilter);
            }

            if (sourceFilter && sourceFilter !== "ALL") {
                params.append("isAutoGenerated", sourceFilter === "AUTO" ? "true" : "false");
            }

            const res = await axios.get(`/api/finance/transactions?${params}`);
            setTransactions(res.data.data);
            setTotal(res.data.total);
            setTotalRevenue(res.data.totalRevenue || 0);
        } catch (error) {
            toast.error("Failed to load transactions");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchData();
    }, [search, page, limit, typeFilter, statusFilter, sourceFilter]);

    const handleAdd = async () => {
        try {
            setSubmitting(true);
            await axios.post("/api/finance/transactions", formData);
            toast.success("Transaction added successfully");
            setIsAddDialogOpen(false);
            resetForm();
            fetchData();
        } catch (error: any) {
            toast.error(error.response?.data?.error || "Failed to add transaction");
        } finally {
            setSubmitting(false);
        }
    };

    const handleEdit = async () => {
        if (!selectedTransaction) return;
        try {
            setSubmitting(true);
            await axios.put("/api/finance/transactions", {
                id: selectedTransaction.id,
                ...formData,
            });
            toast.success("Transaction updated successfully");
            setIsEditDialogOpen(false);
            resetForm();
            fetchData();
        } catch (error: any) {
            toast.error(error.response?.data?.error || "Failed to update transaction");
        } finally {
            setSubmitting(false);
        }
    };

    const handleDelete = async () => {
        if (!selectedTransaction) return;
        try {
            setSubmitting(true);
            await axios.delete(`/api/finance/transactions?id=${selectedTransaction.id}`);
            toast.success("Transaction deleted successfully");
            setIsDeleteDialogOpen(false);
            setSelectedTransaction(null);
            fetchData();
        } catch (error: any) {
            toast.error(error.response?.data?.error || "Failed to delete transaction");
        } finally {
            setSubmitting(false);
        }
    };

    const openEditDialog = (transaction: Transaction) => {
        setSelectedTransaction(transaction);
        setFormData({
            type: transaction.type,
            amount: transaction.amount,
            description: transaction.description,
            transactionDate: new Date(transaction.transactionDate).toISOString().split('T')[0],
            paymentMethod: transaction.paymentMethod || "",
            status: transaction.status,
            notes: transaction.notes || "",
        });
        setIsEditDialogOpen(true);
    };

    const openDeleteDialog = (transaction: Transaction) => {
        setSelectedTransaction(transaction);
        setIsDeleteDialogOpen(true);
    };

    const resetForm = () => {
        setFormData({
            type: "PRODUCT_SALE",
            amount: 0,
            description: "",
            transactionDate: new Date().toISOString().split('T')[0],
            paymentMethod: "",
            status: "COMPLETED",
            notes: "",
        });
        setSelectedTransaction(null);
    };

    const getTypeBadge = (type: string) => {
        const colors: any = {
            PRODUCT_SALE: "bg-blue-100 text-blue-800",
            ANIMAL_SALE: "bg-green-100 text-green-800",
            CONSULTATION_FEE: "bg-purple-100 text-purple-800",
            ADDITIONAL_CONSULTATION: "bg-pink-100 text-pink-800",
            OTHER_INCOME: "bg-gray-100 text-gray-800",
        };
        return colors[type] || "bg-gray-100 text-gray-800";
    };

    const getStatusBadge = (status: string) => {
        const colors: any = {
            COMPLETED: "bg-green-100 text-green-800",
            PENDING: "bg-yellow-100 text-yellow-800",
            CANCELLED: "bg-red-100 text-red-800",
        };
        return colors[status] || "bg-gray-100 text-gray-800";
    };

    const totalPages = Math.ceil(total / limit);

    return (
        <div className="p-6">
            <div className="flex justify-between items-center mb-6">
                <h1 className="text-3xl font-bold text-green-500">Income & Transactions</h1>
                <Button onClick={() => setIsAddDialogOpen(true)} className="bg-green-600 hover:bg-green-700">
                    <Plus className="w-4 h-4 mr-2" />
                    Add Transaction
                </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                <div className="bg-white p-6 rounded-lg border">
                    <div className="flex items-center gap-3">
                        <DollarSign className="h-8 w-8 text-green-500" />
                        <div>
                            <p className="text-sm text-gray-600">Total Revenue</p>
                            <p className="text-2xl font-bold">₨{totalRevenue.toLocaleString()}</p>
                        </div>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-lg border">
                    <div className="flex items-center gap-3">
                        <TrendingUp className="h-8 w-8 text-blue-500" />
                        <div>
                            <p className="text-sm text-gray-600">Total Transactions</p>
                            <p className="text-2xl font-bold">{total}</p>
                        </div>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-lg border">
                    <div className="flex items-center gap-3">
                        <DollarSign className="h-8 w-8 text-purple-500" />
                        <div>
                            <p className="text-sm text-gray-600">Average Transaction</p>
                            <p className="text-2xl font-bold">
                                ₨{total > 0 ? (totalRevenue / total).toFixed(0) : 0}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-4">
                <Input
                    placeholder="Search transactions..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    className="max-w-sm"
                />

                <div className="flex gap-2">
                    <Select value={typeFilter} onValueChange={setTypeFilter}>
                        <SelectTrigger className="w-52">
                            <SelectValue placeholder="Filter by type" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="ALL">All Types</SelectItem>
                            {transactionTypes.map((type) => (
                                <SelectItem key={type} value={type}>
                                    {type.replace(/_/g, " ")}
                                </SelectItem>
                            ))}
                        </SelectContent>
                    </Select>

                    <Select value={statusFilter} onValueChange={setStatusFilter}>
                        <SelectTrigger className="w-32">
                            <SelectValue placeholder="Status" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="ALL">All Status</SelectItem>
                            <SelectItem value="COMPLETED">Completed</SelectItem>
                            <SelectItem value="PENDING">Pending</SelectItem>
                            <SelectItem value="CANCELLED">Cancelled</SelectItem>
                        </SelectContent>
                    </Select>

                    <Select value={sourceFilter} onValueChange={setSourceFilter}>
                        <SelectTrigger className="w-32">
                            <SelectValue placeholder="Source" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="ALL">All Sources</SelectItem>
                            <SelectItem value="AUTO">Auto</SelectItem>
                            <SelectItem value="MANUAL">Manual</SelectItem>
                        </SelectContent>
                    </Select>

                    <Select value={limit.toString()} onValueChange={(val) => setLimit(Number(val))}>
                        <SelectTrigger className="w-28">
                            <SelectValue placeholder="Entries" />
                        </SelectTrigger>
                        <SelectContent>
                            {[10, 25, 50, 100].map((n) => (
                                <SelectItem key={n} value={n.toString()}>
                                    {n} entries
                                </SelectItem>
                            ))}
                        </SelectContent>
                    </Select>
                </div>
            </div>

            <div className="rounded-xl overflow-x-auto border bg-white">
                <Table>
                    <TableHeader>
                        <TableRow className="bg-green-100">
                            <TableHead className="font-semibold">Date</TableHead>
                            <TableHead className="font-semibold">Type</TableHead>
                            <TableHead className="font-semibold">Source</TableHead>
                            <TableHead className="font-semibold">Description</TableHead>
                            <TableHead className="font-semibold">Amount</TableHead>
                            <TableHead className="font-semibold">Payment Method</TableHead>
                            <TableHead className="font-semibold">Status</TableHead>
                            <TableHead className="font-semibold">Actions</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {loading
                            ? Array(limit)
                                  .fill(null)
                                  .map((_, i) => (
                                      <TableRow key={i}>
                                          {[...Array(8)].map((_, j) => (
                                              <TableCell key={j}>
                                                  <Skeleton className="h-4 w-full" />
                                              </TableCell>
                                          ))}
                                      </TableRow>
                                  ))
                            : transactions.map((transaction) => (
                                  <TableRow key={transaction.id} className="hover:bg-gray-50">
                                      <TableCell>
                                          <p className="text-sm">
                                              {new Date(transaction.transactionDate).toLocaleDateString()}
                                          </p>
                                          <p className="text-xs text-gray-500">
                                              {new Date(transaction.transactionDate).toLocaleTimeString()}
                                          </p>
                                      </TableCell>
                                      <TableCell>
                                          <Badge className={getTypeBadge(transaction.type)}>
                                              {transaction.type.replace(/_/g, " ")}
                                          </Badge>
                                      </TableCell>
                                      <TableCell>
                                          <Badge className={transaction.isAutoGenerated ? "bg-blue-100 text-blue-800" : "bg-purple-100 text-purple-800"}>
                                              {transaction.isAutoGenerated ? "Auto" : "Manual"}
                                          </Badge>
                                      </TableCell>
                                      <TableCell>
                                          <p className="text-sm max-w-xs truncate" title={transaction.description}>
                                              {transaction.description}
                                          </p>
                                      </TableCell>
                                      <TableCell>
                                          <span className="font-semibold text-green-600">
                                              ₨{transaction.amount.toLocaleString()}
                                          </span>
                                      </TableCell>
                                      <TableCell>
                                          <p className="text-sm">{transaction.paymentMethod || "-"}</p>
                                      </TableCell>
                                      <TableCell>
                                          <Badge className={getStatusBadge(transaction.status)}>
                                              {transaction.status}
                                          </Badge>
                                      </TableCell>
                                      <TableCell>
                                          <div className="flex gap-2">
                                              <Button
                                                  variant="ghost"
                                                  size="sm"
                                                  onClick={() => openEditDialog(transaction)}
                                              >
                                                  <Edit className="w-4 h-4 text-blue-500" />
                                              </Button>
                                              <Button
                                                  variant="ghost"
                                                  size="sm"
                                                  onClick={() => openDeleteDialog(transaction)}
                                              >
                                                  <Trash2 className="w-4 h-4 text-red-500" />
                                              </Button>
                                          </div>
                                      </TableCell>
                                  </TableRow>
                              ))}
                    </TableBody>
                </Table>
            </div>

            <div className="flex justify-between items-center mt-6">
                <div className="text-sm text-gray-600">
                    Showing {(page - 1) * limit + 1} to {Math.min(page * limit, total)} of {total} entries
                </div>

                <div className="flex items-center gap-2">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setPage((p) => Math.max(1, p - 1))}
                        disabled={page === 1}
                    >
                        <ChevronLeft className="w-4 h-4" />
                    </Button>
                    <div className="text-sm font-medium">{page}</div>
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                        disabled={page >= totalPages}
                    >
                        <ChevronRight className="w-4 h-4" />
                    </Button>
                </div>
            </div>

            {/* Add/Edit Dialog */}
            <Dialog
                open={isAddDialogOpen || isEditDialogOpen}
                onOpenChange={(open) => {
                    if (!open) {
                        setIsAddDialogOpen(false);
                        setIsEditDialogOpen(false);
                        resetForm();
                    }
                }}
            >
                <DialogContent className="max-w-2xl">
                    <DialogHeader>
                        <DialogTitle>
                            {isEditDialogOpen ? "Edit Transaction" : "Add New Transaction"}
                        </DialogTitle>
                    </DialogHeader>

                    <div className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <Label htmlFor="type">Transaction Type *</Label>
                                <Select
                                    value={formData.type}
                                    onValueChange={(value) => setFormData({ ...formData, type: value })}
                                >
                                    <SelectTrigger>
                                        <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {transactionTypes.map((type) => (
                                            <SelectItem key={type} value={type}>
                                                {type.replace(/_/g, " ")}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </div>

                            <div>
                                <Label htmlFor="amount">Amount (₨) *</Label>
                                <Input
                                    id="amount"
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={formData.amount}
                                    onChange={(e) =>
                                        setFormData({ ...formData, amount: parseFloat(e.target.value) })
                                    }
                                    placeholder="0.00"
                                />
                            </div>
                        </div>

                        <div>
                            <Label htmlFor="description">Description *</Label>
                            <Textarea
                                id="description"
                                value={formData.description}
                                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                                placeholder="Transaction description..."
                                rows={3}
                            />
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <Label htmlFor="transactionDate">Transaction Date *</Label>
                                <Input
                                    id="transactionDate"
                                    type="date"
                                    value={formData.transactionDate}
                                    onChange={(e) =>
                                        setFormData({ ...formData, transactionDate: e.target.value })
                                    }
                                />
                            </div>

                            <div>
                                <Label htmlFor="status">Status *</Label>
                                <Select
                                    value={formData.status}
                                    onValueChange={(value) => setFormData({ ...formData, status: value })}
                                >
                                    <SelectTrigger>
                                        <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="COMPLETED">Completed</SelectItem>
                                        <SelectItem value="PENDING">Pending</SelectItem>
                                        <SelectItem value="CANCELLED">Cancelled</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>
                        </div>

                        <div>
                            <Label htmlFor="paymentMethod">Payment Method</Label>
                            <Input
                                id="paymentMethod"
                                value={formData.paymentMethod}
                                onChange={(e) =>
                                    setFormData({ ...formData, paymentMethod: e.target.value })
                                }
                                placeholder="JazzCash, EasyPaisa, Bank Transfer, etc."
                            />
                        </div>

                        <div>
                            <Label htmlFor="notes">Notes</Label>
                            <Textarea
                                id="notes"
                                value={formData.notes}
                                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                                placeholder="Additional notes..."
                                rows={3}
                            />
                        </div>
                    </div>

                    <DialogFooter>
                        <Button
                            variant="outline"
                            onClick={() => {
                                setIsAddDialogOpen(false);
                                setIsEditDialogOpen(false);
                                resetForm();
                            }}
                        >
                            Cancel
                        </Button>
                        <Button
                            onClick={isEditDialogOpen ? handleEdit : handleAdd}
                            disabled={submitting}
                            className="bg-green-600 hover:bg-green-700"
                        >
                            {submitting ? (
                                <>
                                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                    Saving...
                                </>
                            ) : isEditDialogOpen ? (
                                "Update Transaction"
                            ) : (
                                "Add Transaction"
                            )}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* Delete Dialog */}
            <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Confirm Deletion</DialogTitle>
                    </DialogHeader>
                    <p>Are you sure you want to delete this transaction? This action cannot be undone.</p>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsDeleteDialogOpen(false)}>
                            Cancel
                        </Button>
                        <Button variant="destructive" onClick={handleDelete} disabled={submitting}>
                            {submitting ? (
                                <>
                                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                    Deleting...
                                </>
                            ) : (
                                "Delete"
                            )}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    );
}
