import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { z } from 'zod'

export const runtime = 'nodejs'
export const maxDuration = 60

// Validation schemas
const transactionSchema = z.object({
  type: z.enum(['PRODUCT_SALE', 'ANIMAL_SALE', 'CONSULTATION_FEE', 'ADDITIONAL_CONSULTATION', 'OTHER_INCOME']),
  amount: z.number().min(0),
  description: z.string().min(1),
  transactionDate: z.string().or(z.date()),
  paymentMethod: z.string().optional().nullable(),
  status: z.enum(['PENDING', 'COMPLETED', 'CANCELLED']).default('COMPLETED'),
  checkoutId: z.number().optional().nullable(),
  appointmentId: z.number().optional().nullable(),
  additionalFeeId: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
})

// GET - Fetch all transactions with filtering
export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url)
    const search = searchParams.get('search') || ''
    const type = searchParams.get('type')
    const status = searchParams.get('status')
    const isAutoGenerated = searchParams.get('isAutoGenerated')
    const startDate = searchParams.get('startDate')
    const endDate = searchParams.get('endDate')
    const limit = parseInt(searchParams.get('limit') || '10', 10)
    const page = parseInt(searchParams.get('page') || '1', 10)
    const skip = (page - 1) * limit

    const where: any = {
      OR: [
        { description: { contains: search } },
        { notes: { contains: search } },
      ],
    }

    if (type) {
      where.type = type
    }

    if (status) {
      where.status = status
    }

    if (isAutoGenerated !== null && isAutoGenerated !== undefined) {
      where.isAutoGenerated = isAutoGenerated === 'true'
    }

    if (startDate || endDate) {
      where.transactionDate = {}
      if (startDate) {
        where.transactionDate.gte = new Date(startDate)
      }
      if (endDate) {
        where.transactionDate.lte = new Date(endDate)
      }
    }

    const [transactions, total, stats] = await Promise.all([
      prisma.transaction.findMany({
        where,
        skip,
        take: limit,
        orderBy: { transactionDate: 'desc' },
      }),
      prisma.transaction.count({ where }),
      prisma.transaction.aggregate({
        where: { status: 'COMPLETED' },
        _sum: {
          amount: true,
        },
      }),
    ])

    return NextResponse.json({
      data: transactions,
      total,
      page,
      limit,
      totalRevenue: stats._sum.amount || 0,
    })
  } catch (error) {
    console.error('Error fetching transactions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch transactions' },
      { status: 500 }
    )
  }
}

// POST - Create new transaction
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const validation = transactionSchema.safeParse(body)

    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.errors[0].message },
        { status: 400 }
      )
    }

    const transaction = await prisma.transaction.create({
      data: {
        ...validation.data,
        transactionDate: new Date(validation.data.transactionDate),
      },
    })

    return NextResponse.json(transaction, { status: 201 })
  } catch (error) {
    console.error('Error creating transaction:', error)
    return NextResponse.json(
      { error: 'Failed to create transaction' },
      { status: 500 }
    )
  }
}

// PUT - Update transaction
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json()
    const { id, ...updateData } = body

    if (!id) {
      return NextResponse.json(
        { error: 'Transaction ID is required' },
        { status: 400 }
      )
    }

    const validation = transactionSchema.partial().safeParse(updateData)

    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.errors[0].message },
        { status: 400 }
      )
    }

    const dataToUpdate = { ...validation.data }
    if (dataToUpdate.transactionDate) {
      dataToUpdate.transactionDate = new Date(dataToUpdate.transactionDate)
    }

    const transaction = await prisma.transaction.update({
      where: { id: parseInt(id) },
      data: dataToUpdate,
    })

    return NextResponse.json(transaction)
  } catch (error) {
    console.error('Error updating transaction:', error)
    return NextResponse.json(
      { error: 'Failed to update transaction' },
      { status: 500 }
    )
  }
}

// DELETE - Delete transaction
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const id = searchParams.get('id')

    if (!id) {
      return NextResponse.json(
        { error: 'Transaction ID is required' },
        { status: 400 }
      )
    }

    await prisma.transaction.delete({
      where: { id: parseInt(id) },
    })

    return NextResponse.json(
      { message: 'Transaction deleted successfully' },
      { status: 200 }
    )
  } catch (error) {
    console.error('Error deleting transaction:', error)
    return NextResponse.json(
      { error: 'Failed to delete transaction' },
      { status: 500 }
    )
  }
}
